version: '3'

services:
  frontend:
    build: ./
    container_name: sports-ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  backend:
    container_name: sports-data-server
    image: abosch1/sports-data-server:latest
    restart: always
    ports:
      - "8081:8081"
